### ISSUE TITLE
Update API url to api.track.toggl.com

### ISSUE THREAD

**Issue by brentonrace** [panoramicdata/Toggl.Api#1]
We've been using this library for an internal tool that interacts with the Toggl API, and it has been working great.

We recently got the following email from Toggl, so just wanted to check if its on your radar to update this code to use the new urls? Thanks!

![image](https://user-images.githubusercontent.com/15177181/118394496-6cacbf00-b688-11eb-81dc-6ca77f786075.png)

**Comment by davidnmbond** [comment]
Hey @brentonrace,

We're glad that the library is useful!  I gave it a bit of a revamp over the weekend, including updates to these URLs.

Best wishes,

David
